# Generated by Django 6.0.5 on 2026-05-29 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("titotech", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Descripción"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "db_table": "titotech_categories",
                "ordering": ["name"],
            },
        ),
        migrations.RenameModel(
            old_name="OrderItem",
            new_name="OrderDetail",
        ),
        migrations.DeleteModel(
            name="Accessory",
        ),
        migrations.AlterModelOptions(
            name="orderdetail",
            options={
                "verbose_name": "Detalle de Pedido",
                "verbose_name_plural": "Detalles de Pedido",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category", "brand", "model"],
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="compatibility",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Para accesorios: modelos compatibles. Ej: Samsung Galaxy S25, iPhone 15",
                verbose_name="Compatibilidad",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Marca"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="Color"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/", verbose_name="Imagen"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="model",
            field=models.CharField(max_length=200, verbose_name="Modelo / Nombre"),
        ),
        migrations.AlterField(
            model_name="product",
            name="ram",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="RAM"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="storage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "N/A"),
                    ("32GB", "32 GB"),
                    ("64GB", "64 GB"),
                    ("128GB", "128 GB"),
                    ("256GB", "256 GB"),
                    ("512GB", "512 GB"),
                    ("1TB", "1 TB"),
                ],
                default="",
                max_length=10,
                verbose_name="Almacenamiento",
            ),
        ),
        migrations.AlterModelTable(
            name="order",
            table="titotech_orders",
        ),
        migrations.AlterModelTable(
            name="orderdetail",
            table="titotech_orderdetails",
        ),
        migrations.AlterModelTable(
            name="product",
            table="titotech_products",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="titotech.category",
                verbose_name="Categoría",
            ),
        ),
    ]
