# Generated by Django 6.0.5 on 2026-05-29 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("titotech", "0004_category_not_null_drop_accessory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to="titotech.customerprofile",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carrito de Compras",
                "verbose_name_plural": "Carritos de Compras",
                "db_table": "titotech_carts",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Cantidad"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Agregado el"),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="titotech.cart",
                        verbose_name="Carrito",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="titotech.product",
                        verbose_name="Producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de Carrito",
                "verbose_name_plural": "Ítems de Carrito",
                "db_table": "titotech_cartitems",
                "unique_together": {("cart", "product")},
            },
        ),
    ]
