# Generated by Django 6.0.5 on 2026-05-31 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("titotech", "0005_cart_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Imagen (URL o ruta local)",
            ),
        ),
    ]
